### ISSUE TITLE
Define user interface needs

### ISSUE THREAD

**Issue by bigemfat** [Dave-Poissant/Project-SLEARH#18]

**Comment by Dave-Poissant** [comment]
-> Indicator that shows the Pi-arduino connection's state;
-> Input text field, for the user;
-> A visual help for the user, to show where the process is;
-> Button to send the text to the back-end;
-> Stop button;
-> Indicator that shows if the hand is currently executing a command or if it's in idle state;
-> Manual mode and "Next letter" button;
-> A glider to select the time it takes before the next letter command is executed (If not in manual mode);
-> (Facultative) Hand simulation to show that the right commands are sent if the physical hand does not work;
-> Pause button;
-> Mode selector (Test/Quiz);
-> Warning of some sort if a letter isn't supported.
