### ISSUE TITLE
Define the back end programming classes and functions

### ISSUE THREAD

**Issue by bigemfat** [Dave-Poissant/Project-SLEARH#21]

**Comment by JerSamson** [comment]
**RaspberryPi classes*

1.  TextAnalyser
- Extract characters from the input text box
- Creates Event object
- Sends Events into the "Event table"

2. Event
- Has a name (character)

3. Event Handler
- Has its own thread: Executes the events in its table
- Has a private Event table
- Calls "Send comm."

4. Communication
- Communicates with the Arduino using a mutex lock condition
- Json
- Json string includes Ticket 

5. Configuration
- Enum : Parameters / Options
- Has attributes for every parameter
